use super::JobsError;

impl JobsError {
    pub fn code(&self) -> &'static str {
        match self {
            Self::NotUuidV7 { .. } => "not_uuid_v7",
            Self::BlankValue { .. } => "blank_value",
            Self::InvalidSegment { .. } => "invalid_segment",
            Self::ValueTooLong { .. } => "value_too_long",
            Self::InvalidJitter => "invalid_jitter",
            Self::InvalidRetryFactor => "invalid_retry_factor",
            Self::InvalidDuration { .. } => "invalid_duration",
            Self::OutOfRange { .. } => "out_of_range",
            Self::NotAJsonObject { .. } => "not_a_json_object",
            Self::JobIdConflict { .. } => "job_id_conflict",
            Self::SourceAlreadyActive { .. } => "source_already_active",
            Self::ParentJobUnknown { .. } => "parent_job_unknown",
            Self::ParentJobTerminal { .. } => "parent_job_terminal",
            Self::ParentJobDeleted { .. } => "parent_job_deleted",
            Self::SelfReference { .. } => "self_reference",
            Self::MaxAttemptsAboveCeiling { .. } => "max_attempts_above_ceiling",
            Self::JobAlreadyTerminal { .. } => "job_already_terminal",
            Self::JobDeleted => "job_deleted",
            Self::JobNotTerminal { .. } => "job_not_terminal",
            Self::JobAlreadyDeleted => "job_already_deleted",
            Self::JobNotFailed { .. } => "job_not_failed",
            Self::JobNotInProgress { .. } => "job_not_in_progress",
            Self::NotOwner => "not_owner",
            Self::SuccessorStillActive { .. } => "successor_still_active",
            Self::ManualRetryAlreadyStarted { .. } => "manual_retry_already_started",
            Self::ManualRetryConflict { .. } => "manual_retry_conflict",
            Self::StaleFailedResolution { .. } => "stale_failed_resolution",
            Self::JobStillActive => "job_still_active",
            Self::InactivityTimeoutNotReached { .. } => "inactivity_timeout_not_reached",
            Self::RunNotFound { .. } => "run_not_found",
            Self::RunAlreadyInFlight { .. } => "run_already_in_flight",
            Self::RunNotStarted { .. } => "run_not_started",
            Self::RunWithinMaxDuration { .. } => "run_within_max_duration",
            Self::RunnerTypeMismatch { .. } => "runner_type_mismatch",
            Self::RunnerTypeUnavailable { .. } => "runner_type_unavailable",
            Self::RunnerTypeRetired { .. } => "runner_type_retired",
            Self::RunnerTypeNotActive { .. } => "runner_type_not_active",
            Self::RunnerTypeNotDeprecated { .. } => "runner_type_not_deprecated",
            Self::RunnerTypeAlreadyActive => "runner_type_already_active",
            Self::RunnerTypeHasNonTerminalJobs { .. } => "runner_type_has_non_terminal_jobs",
            Self::RunnerTypeHasRecentTerminalRuns { .. } => "runner_type_has_recent_terminal_runs",
            Self::RunnerTypeHasNoLiveInstances => "runner_type_has_no_live_instances",
            Self::RetryBudgetExhausted { .. } => "retry_budget_exhausted",
            Self::RetryNotScheduled => "retry_not_scheduled",
            Self::RetryNotDue { .. } => "retry_not_due",
            Self::EmptyPlan => "empty_plan",
            Self::DuplicatePlanStepIndex { .. } => "duplicate_plan_step_index",
            Self::InstanceNotLive { .. } => "instance_not_live",
            Self::StaleLoss { .. } => "stale_loss",
            Self::CorruptState { .. } => "corrupt_state",
            Self::UnknownEnumValue { .. } => "unknown_enum_value",
            Self::Serialization { .. } => "serialization_failed",
        }
    }
}
