use thiserror::Error;

/// Every way a `jobs` command can refuse.
///
/// Layer one of the three-layer error contract: invariant violations, in the
/// domain's own vocabulary. It names no HTTP status and no GraphQL code on
/// purpose — the service layer categorises these, the edge maps them to stable
/// codes, and neither concern is allowed to leak back down here.
#[derive(Debug, Error)]
pub enum JobsError {
    /// The aggregate id the caller supplied is already in use.
    ///
    /// Ids are generated by the creator, never by this service, so every
    /// `create_*` command has to guard reuse rather than assume it away — this
    /// is the variant that guard returns.
    #[error("aggregate id already used")]
    IdAlreadyUsed,

    /// A domain payload could not be serialized to, or read back from, its
    /// stored JSON form.
    #[error("serialization failed: {0}")]
    Serialization(String),
}

/// Event payloads round-trip through JSON on their way to and from the event
/// store, so a `serde_json` failure is a domain-visible outcome rather than an
/// infrastructure detail the caller can ignore.
impl From<serde_json::Error> for JobsError {
    fn from(error: serde_json::Error) -> Self {
        Self::Serialization(error.to_string())
    }
}
